const INVALID_DATA_ERROR_CODE = 400;
const UNATHORIZED_ERROR_CODE = 401;
const PERMISSION_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const DUPLICATE_ERROR_CODE = 409;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  INVALID_DATA_ERROR_CODE,
  UNATHORIZED_ERROR_CODE,
  PERMISSION_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  DUPLICATE_ERROR_CODE,
  DEFAULT_ERROR_CODE,
};
